import type { Settlement } from '@entities/Settlement';
import type { Hex } from '@entities/Hex';
import type { Resources } from '../types';
import { getHexesInRadius } from './map-generator';

/**
 * Calculate resources generated by a settlement from controlled territory
 */
export function calculateTerritoryResources(
    settlement: Settlement,
    grid: Map<string, Hex>
): Resources {
    const resources: Resources = {
        food: 0,
        production: 0,
        gold: 0,
        wood: 0,
        apricorns: 0,
        leppa_berries: 0,
        rare_candy: 0
    };

    // Base settlement output
    resources.food = 2;
    resources.production = 1;

    // Scan territory
    const territoryHexes = getHexesInRadius(grid, settlement, settlement.territoryRadius);

    territoryHexes.forEach(hex => {
        if (hex.owner === settlement.owner) {
            const yield_ = hex.getResourceYield();

            // Add each resource from hex yield
            if (yield_.food) resources.food += yield_.food;
            if (yield_.production) resources.production += yield_.production;
            if (yield_.gold) resources.gold += yield_.gold;
            if (yield_.wood) resources.wood += yield_.wood;
            if (yield_.apricorns) resources.apricorns += yield_.apricorns;
            if (yield_.leppa_berries) resources.leppa_berries += yield_.leppa_berries;
        }
    });

    // Candy Factory bonus
    if (settlement.buildings.candyFactory) {
        resources.rare_candy += 0.5;
    }

    // Round all resources (handles fractional accumulation)
    for (const key in resources) {
        resources[key as keyof Resources] = Math.floor(resources[key as keyof Resources]);
    }

    return resources;
}

/**
 * Process resource generation for all settlements at turn end
 */
export function processResourceGeneration(
    settlements: Settlement[],
    factionResources: Record<string, Resources>,
    grid: Map<string, Hex>
): void {
    settlements.forEach(settlement => {
        const generated = calculateTerritoryResources(settlement, grid);

        const faction = settlement.owner;
        if (factionResources[faction]) {
            // Add generated resources to faction's pool
            for (const key in generated) {
                factionResources[faction][key as keyof Resources] += generated[key as keyof Resources];
            }
        }
    });
}
